TRIBUNAL_CODES = {
'2': '1º Juzgado de Letras de Arica',
'1400': '1º Juzgado De Letras de Arica ex 4°',
'3': '2º Juzgado de Letras de Arica',
'1401': '2º Juzgado De Letras de Arica ex 4°',
'5': '3º Juzgado de Letras de Arica Ex 4º',
'4': '3º Juzgado de Letras de Arica',
'6': 'Juzgado de Letras y Gar. Pozo Almonte',
'9': '1º Juzgado de Letras de Iquique',
'10': '2º Juzgado de Letras de Iquique',
'11': '3º Juzgado de Letras de Iquique',
'13': 'Juzgado de Letras Tocopilla',
'14': 'Juzgado de Letras y Gar.de María Elena',
'16': '1º Juzgado de Letras de Calama',
'17': '2º Juzgado de Letras de Calama',
'658': '3º Juzgado de Letras de Calama',
'26': 'Juzgado de Letras y Gar. de Taltal',
'1041': '1º Juzgado de Letras Civil de Antofagasta',
'1042': '2º Juzgado de Letras Civil de Antofagasta',
'1043': '3º Juzgado de Letras Civil de Antofagasta',
'1044': '4 ° Juzgado de Letras Civil de Antofagasta',
'1501': 'Juzgado de Letras y Garantía Mejillones',
'27': 'Juzgado de Letras y Gar. de Chañaral',
'29': 'Juzgado de Letras de Diego de Almagro',
'31': '1º Juzgado de Letras de Copiapó',
'32': '2º Juzgado de Letras de Copiapó',
'33': '3º Juzgado de Letras de Copiapó',
'34': 'Juzgado de Letras y Gar.de Freirina',
'926': '4º Juzgado de Letras de Copiapó',
'36': '1º Juzgado de Letras de Vallenar',
'37': '2º Juzgado de Letras de Vallenar',
'386': 'Juzgado de Letras y Gar.de Caldera',
'40': '1º Juzgado de Letras de la Serena',
'41': '2º Juzgado de Letras de la Serena',
'42': '3º Juzgado de Letras de la Serena',
'43': '1º Juzgado de Letras de Coquimbo',
'44': '2º Juzgado de Letras de Coquimbo',
'45': '3º Juzgado de Letras de Coquimbo',
'46': 'Juzgado de Letras de Vicuña',
'47': 'Juzgado de letras y garantía de Andacollo',
'48': '1º Juzgado de Letras de Ovalle',
'49': '2º Juzgado de Letras de Ovalle',
'50': '3º Juzgado de Letras de Ovalle',
'51': 'Juzgado de Letras y Gar.de Combarbalá',
'52': 'Juzgado de Letras de Illapel',
'53': 'Juzgado de Letras y Gar. de los Vilos',
'56': '1º Juzgado Civil de Valparaíso',
'55': '2º Juzgado Civil de Valparaíso',
'54': '3º Juzgado Civil de Valparaíso',
'59': '4º Juzgado Civil de Valparaíso',
'60': '5º Juzgado Civil de Valparaíso',
'57': '1º Juzgado Civil de Viña del Mar',
'58': '2º Juzgado Civil de Viña del Mar',
'61': '3º Juzgado Civil de Viña del Mar',
'83': '1º Juzgado de Letras de Quilpue',
'84': '2º Juzgado de Letras de Quilpue',
'85': 'Juzgado de Letras de Villa Alemana',
'86': 'Juzgado de Letras de Casablanca',
'87': 'Juzgado de Letras de La Ligua',
'88': 'Juzgado de Letras y Gar. de Petorca',
'89': '1º Juzgado de Letras de Los Andes',
'90': '2º Juzgado de Letras de Los Andes',
'93': '1º Juzgado de Letras de San Felipe Ex 2º',
'92': '1º Juzgado de Letras de San Felipe',
'94': 'Juzgado de Letras y Gar.de Putaendo',
'96': '1º Juzgado de Letras de Quillota',
'97': '2º Juzgado de Letras de Quillota',
'98': 'Juzgado de Letras de La Calera',
'99': 'Juzgado de Letras de Limache',
'101': '1º Juzgado de Letras de San Antonio',
'102': '2º Juzgado de Letras de San Antonio',
'103': 'Juzgado de Letras y Gar. de Isla de Pascua',
'660': 'Juzgado de Letras y Gar.de Quintero',
'110': '1º Juzgado Civil de Rancagua',
'969': '2º Juzgado Civil de Rancagua',
'111': '1º Juzgado de Letras de Rengo',
'113': 'Juzgado de Letras de San Vicente de Tagua Tagua',
'114': '1º Juzgado de Letras y Gar.de Peumo',
'115': '1º Juzgado de Letras de San Fernando',
'116': '2º Juzgado de Letras de San Fernando',
'118': '1º Juzgado De Letras De Santa Cruz Ex 2°',
'117': '1º Juzgado de Letras de Santa Cruz',
'119': 'Juzgado de Letras y Gar.de Pichilemu',
'1150': 'Juzgado de Letras y Gar.de Litueche',
'1151': 'Juzgado de Letras y Gar.de Peralillo',
'122': '1º Juzgado de Letras de Talca',
'123': '2º Juzgado de Letras de Talca',
'124': '3º Juzgado de Letras de Talca',
'125': '4º Juzgado de Letras de Talca',
'126': 'Juzgado de Letras de Constitución',
'127': 'Juzgado De Letras Y Gar. de Curepto',
'129': '1º Juzgado de Letras de Curicó',
'130': '2º Juzgado de Letras de Curicó',
'131': '2º Juzgado de Letras de Curicó Ex 3°',
'132': 'Juzgado De Letras Y Gar. de Licantén',
'133': 'Juzgado de Letras de Molina',
'135': '1º Juzgado de Letras de Linares',
'136': '2º Juzgado de Letras de Linares',
'138': 'Juzgado de Letras de San Javier',
'139': 'Juzgado de Letras de Cauquenes',
'140': 'Juzgado de Letras y Gar. de Chanco',
'141': 'Juzgado de Letras de Parral',
'145': '1º Juzgado Civil de Chillán',
'146': '2º Juzgado Civil de Chillán',
'147': '1º Juzgado de Letras de San Carlos',
'149': 'Juzgado de Letras de Yungay',
'150': 'Juzgado de Letras y Gar. de Bulnes',
'151': 'Juzgado de Letras y Gar.de Coelemu',
'152': 'Juzgado de Letras y Gar.de Quirihue',
'154': '1º Juzgado de Letras de Los Angeles',
'156': '2° Juzgado de Letras de Los Angeles ex 3°',
'155': '2º Juzgado de Letras de Los Angeles',
'157': 'Juzgado de Letras y Gar. de Mulchen',
'158': 'Juzgado de Letras y Gar.de Nacimiento',
'159': 'Juzgado de Letras y Gar.de Laja',
'160': 'Juzgado de Letras y Gar.de Yumbel',
'161': '1º Juzgado Civil de Concepción',
'162': '2º Juzgado Civil de Concepción',
'163': '3º Juzgado Civil de Concepción',
'179': '1º Juzgado Civil de Talcahuano',
'180': '2º Juzgado Civil de Talcahuano',
'187': 'Juzgado de Letras de Tomé',
'188': 'Juzgado de Letras y Gar.de Florida',
'189': 'Juzgado de Letras y Gar.de Santa Juana',
'190': 'Juzgado de Letras y Gar. de Lota',
'191': '1º Juzgado de Letras de Coronel',
'192': '2º Juzgado de Letras de Coronel',
'193': 'Juzgado de Letras y Gar.de Lebu',
'194': 'Juzgado de Letras de Arauco',
'195': 'Juzgado de Letras y Gar.de Curanilahue',
'196': 'Juzgado de Letras de Cañete',
'385': 'Juzgado de Letras y Gar. Santa Bárbara',
'1152': 'Juzgado de Letras y Gar.de Cabrero',
'197': '1º Juzgado Civil de Temuco',
'198': '2º Juzgado Civil de Temuco',
'204': 'Juzgado de Letras de Angol',
'206': 'Juzgado de Letras y Gar.de Collipulli',
'207': 'Juzgado de Letras y Gar.de Traiguén',
'208': 'Juzgado de Letras de Victoria',
'209': 'Juzgado de Letras y Gar.de Curacautin',
'210': 'Juzgado de Letras Loncoche',
'211': 'Juzgado de Letras de Pitrufquen',
'212': 'Juzgado de Letras de Villarrica',
'213': 'Juzgado de Letras de Nueva Imperial',
'214': 'Juzgado de Letras y Gar.de Pucón',
'215': 'Juzgado de Letras de Lautaro',
'216': 'Juzgado de Letras y Gar.de Carahue',
'406': '3º Juzgado Civil de Temuco',
'946': 'Juzgado de Letras y Gar.de Tolten',
'947': 'Juzgado de Letras y Gar.de Puren',
'220': '1º Juzgado Civil de Valdivia',
'221': '2º Juzgado Civil de Valdivia',
'222': 'Juzgado de Letras de Mariquina',
'223': 'Juzgado de Letras y Gar.de Paillaco',
'224': 'Juzgado de Letras Los Lagos',
'225': 'Juzgado de Letras y Gar. de Panguipulli',
'226': 'Juzgado de Letras y Gar.de la Unión',
'227': 'Juzgado de Letras y Gar.de Río Bueno',
'229': '1º Juzgado de Letras de Osorno',
'230': '2º Juzgado de Letras de Osorno',
'233': 'Juzgado de Letras de Rio Negro',
'237': '1º Juzgado Civil de Puerto Montt',
'1012': '2º Juzgado Civil de Puerto Montt',
'238': 'Juzgado de Letras de Puerto Varas',
'240': 'Juzgado de Letras y Gar.de Calbuco',
'241': 'Juzgado de Letras y Gar. de Maullin',
'242': 'Juzgado de Letras de Castro',
'243': 'Juzgado de Letras de Ancud',
'244': 'Juzgado de Letras y Garantía de Achao',
'245': 'Juzgado de Letras y Gar. de Chaitén',
'659': 'Juzgado de Letras y Gar. de Los Muermos',
'662': 'Juzgado de Letras y Gar. de Quellón',
'1013': 'Juzgado de Letras y Gar. de Hualaihue',
'246': '1º Juzgado de Letras de Coyhaique',
'247': '1º Juzgado de Letras de Coyhaique Ex 2º',
'248': 'Juzgado de Letras y Gar.de pto.Aysen',
'249': 'Juzgado de Letras y Gar.de Chile Chico',
'250': 'Juzgado de Letras y Gar.de Cochrane',
'996': 'Juzgado de Letras y Gar.de Puerto Cisnes',
'253': '1º Juzgado de Letras de Punta Arenas',
'254': '2º Juzgado de Letras de Punta Arenas',
'255': '3º Juzgado de Letras de Punta Arenas',
'257': 'Juzgado de Letras y Gar. de Puerto Natales',
'258': 'Juzgado de Letras y Gar.de Porvenir',
'1502': 'Juzgado de Letras y Garantía de Cabo de Hornos',
'259': '1º Juzgado Civil de Santiago',
'260': '2º Juzgado Civil de Santiago',
'261': '3º Juzgado Civil de Santiago',
'262': '4º Juzgado Civil de Santiago',
'263': '5º Juzgado Civil de Santiago',
'264': '6º Juzgado Civil de Santiago',
'265': '7º Juzgado Civil de Santiago',
'266': '8º Juzgado Civil de Santiago',
'267': '9º Juzgado Civil de Santiago',
'268': '10º Juzgado Civil de Santiago',
'269': '11º Juzgado Civil de Santiago',
'270': '12º Juzgado Civil de Santiago',
'271': '13º Juzgado Civil de Santiago',
'272': '14º Juzgado Civil de Santiago',
'273': '15º Juzgado Civil de Santiago',
'274': '16º Juzgado Civil de Santiago',
'275': '17º Juzgado Civil de Santiago',
'276': '18º Juzgado Civil de Santiago',
'277': '19º Juzgado Civil de Santiago',
'278': '20º Juzgado Civil de Santiago',
'279': '21º Juzgado Civil de Santiago',
'280': '22º Juzgado Civil de Santiago',
'281': '23º Juzgado Civil de Santiago',
'282': '24º Juzgado Civil de Santiago',
'283': '25º Juzgado Civil de Santiago',
'284': '26º Juzgado Civil de Santiago',
'285': '27º Juzgado Civil de Santiago',
'286': '28º Juzgado Civil de Santiago',
'287': '29º Juzgado Civil de Santiago',
'288': '30º Juzgado Civil de Santiago',
'387': 'Juzgado de Letras de Colina',
'343': '1º Juzgado Civil de San Miguel',
'344': '2º Juzgado Civil de San Miguel',
'345': '3º Juzgado Civil de San Miguel',
'390': '4º Juzgado Civil de San Miguel',
'364': '1º Juzgado Civil de Puente Alto',
'373': '1º Juzgado De Letras De Talagante',
'374': '2º Juzgado De Letras De Talagante',
'375': '1º Juzgado de Letras de Melipilla',
'377': '1º Juzgado de Letras de Buin',
'378': '2º Juzgado de Letras de Buin',
'388': 'Juzgado de Letras de Peñaflor',
'400': '1º Juzgado de Letras de San Bernardo',
'1402': '1º Juzgado de Letras de San Bernardo Ex 3°',
'401': '2º Juzgado de Letras de San Bernardo',
'1403': '2º Juzgado de Letras de San Bernardo Ex 3°'
}